<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Athena.Serilog.Sinks.ZincSearch</AssemblyName>
        <Description>A Serilog sink sending log events to ZincSearch</Description>
        <LangVersion>10</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <!--SourceLink -->
        <!--        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>-->
        <!--        <DebugType>embedded</DebugType>-->
        <!--        <EmbedUntrackedSources>true</EmbedUntrackedSources>-->
        <!--        <PublishRepositoryUrl>true</PublishRepositoryUrl>-->
        <!--        <RepositoryUrl>https://github.com/serilog-contrib/serilog-sinks-grafana-loki.git</RepositoryUrl>-->
        <!--NuGet package-->
        <!--        <PackageIcon>serilog-sink-nuget.png</PackageIcon>-->
        <PackageId>Athena.Serilog.Sinks.ZincSearch</PackageId>
        <!--        <PackageLicenseFile>LICENSE</PackageLicenseFile>-->
        <PackageProjectUrl>https://github.com/e-athena/basic-building-blocks</PackageProjectUrl>
<!--        <PackageReadmeFile>README.md</PackageReadmeFile>-->
        <PackageReleaseNotes>For release notes, please see the change log on GitHub.</PackageReleaseNotes>
        <PackageTags>serilog;zincsearch;sinks</PackageTags>
        <Version>8.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.0.1" />
        <PackageReference Include="System.Text.Json" Version="8.0.4" />
    </ItemGroup>
</Project>
