global using System.Reflection;
global using System.Xml;
global using System.Xml.XPath;
global using Athena.Infrastructure.DataPermission.Attributes;
global using Athena.Infrastructure.DataPermission.Models;
global using Athena.Infrastructure.Enums;
global using Athena.Infrastructure.FrontEndTables;
global using Athena.Infrastructure.QueryFilters;
global using Athena.Infrastructure.Summaries;