// Global using directives

global using Athena.Infrastructure.Event.DomainEvents;
global using System.Linq.Expressions;
global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Reflection;
global using System.Text.Json;
global using Athena.Infrastructure.Attributes;
global using Athena.Infrastructure.Auths;
global using Athena.Infrastructure.DataPermission;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using FreeSql;
global using FreeSql.Internal;
global using DataType = FreeSql.DataType;
global using Athena.Infrastructure.Messaging.Requests;
global using Athena.Infrastructure.Messaging.Responses;
global using Athena.Infrastructure.Domain;
global using Athena.Infrastructure.Exceptions;
global using Athena.Infrastructure.Domain.Attributes;
global using Athena.Infrastructure.Enums;
global using Athena.Infrastructure.Event.IntegrationEvents;
global using Athena.Infrastructure.FreeSql.CAPs;
global using DotNetCore.CAP;
global using MediatR;
global using Athena.Infrastructure.Helpers;
global using Athena.Infrastructure.Expressions;
global using Athena.Infrastructure.FreeSql.Helpers;
global using Athena.Infrastructure.FreeSql.Tenants;
global using Athena.Infrastructure.FreeSql.OTel;
global using Athena.Infrastructure.Providers;
global using Athena.Infrastructure.QueryFilters;
global using Athena.Infrastructure.Tenants;
